version: '3.7'

services:
    fmd:
        # ERROR: manifest for registry.gitlab.com/nulide/findmydeviceserver not found: manifest unknown: manifest unknown
        #image: registry.gitlab.com/nulide/findmydeviceserver
        build:
          context: .
          dockerfile: Dockerfile
        container_name: fmd
        hostname: fmd
        restart: always
        ports:
         - '127.0.0.1:1020:1020'
        volumes:
            - './data:/fmd/objectbox/'
