version: '3.7'

services:
    fmd:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: fmd
        hostname: fmd
        restart: always
        ports:
         - 1020:1020
        volumes:
            - ./data:/fmd/objectbox/
